### ISSUE TITLE
In Signals dictionary, if useEarthMotion=True, then astropy fails to compute LSMT from binary coalescence time if it is too long, i.e ~> Myr

### ISSUE THREAD

**Issue by nsteinle** [CosmoStatGW/gwfast#4]
I'm using gwfast to compute the SNR of binary neutron stars that merge within the age of the Universe. These BNSs are produced from a population synthesis code and thus each comes with a GW coalescence time, t_coal. 

For a given detector, ie the CE with 40km baseline sensitivity, in the Signals dictionary if useEarthMotion=True, then astropy fails to compute LSMT from t_coal if it is too long, i.e ~> Myr, and gives an error because astropy does not know the motion of the Earth far in the future. See the astropy issue discussion here: https://github.com/astropy/astropy/issues/16294

Am I misusing this flag/feature? For now I can just set useEarthMotion=False and pass t_coal to the waveform to avoid the error from astropy when computing LMST from t_GPS via gwfastUtils.GPSt_to_LMST(). 

Is this feature not appropriate for astrophysically derived coalescence timescales, or am I missing something here?

Thanks!

**Comment by FrancescoIacovelli** [comment]
Hi, sorry again for the late reply. This is not really something to fix on the astropy side, as discussed in the issue you opened there. 

What the time parameter in gwfast stands for is essentially a relative rotation of the Earth, _not linked to the redshift_, so passing a value for the GPS time relative to today or a Myr from now (and resulting in the same GMST) makes no difference at all.

Anyway, given that troubles could arise already for relatively low time spans, I added a function independent from astropy (which is anyway **approximate**) to make the calculation, see [here](https://gwfast.readthedocs.io/en/latest/_modules/gwfast/gwfastUtils.html#GPSt_to_GMST_alt). 

Best,

Francesco
